거래내역 DTO 추가
AI-Funding/AI_Funding_BE pull request #31
Opened 2022-02-16 14:13 UTC by JeonHyerim86

2022-02-16 15:44 UTC, kwYoohae commented
현재 저희가 정의한 `Json` 형식은 다음과 같습니다. 

```json
{
	"trade_history" : [
		{
			"stock_name" : "종목 이름",
			"trade_date" : "거래 날짜",
			"total_price" : "거래 금액",
			"trade_type" : "거래 종류",
			"trade_amount" : "거래 수량",
			"current_price" : "단가",
			"trade_price" : "매수/도 가"
		}
	]
}
```

하지만 DTO의 반환에서는 설정을 안해주어서 그냥 카멜케이스로 반환받게 됩니다. 

그래서 `Json`으로 반환할때는 변환해주는 애너테이션이라던지 방법을 찾아서 하시면 좋을것 같습니다 😄

2022-02-16 15:45 UTC, kwYoohae reviewed
`HistoryRequestDto` 는 현재 만들어진 `UserRequestDto`와 같은 내용이기 때문에 없어도 좋을 것 같습니다 👍

2022-02-16 15:46 UTC, kwYoohae reviewed
현재 `HistoryResponseDto` 는 `List<HistoryResponseDto>` 하나만 가지고 있기 때문에 

저는 굳이 없어도 될것같은데 다른 분들은 어떻게 생각하시나요?

2022-02-17 04:50 UTC, HoSeong0731 requested changes
리뷰 내용 확인해주시고 코드 개정 부탁드립니다!
고생 많으셨어요 :)

2022-02-17 04:50 UTC, HoSeong0731 commented on src/main/java/com/AiFunding/ToBi/dto/Tab/History/HistoryRequestDto.java
> +}
https://github.com/AI-Funding/AI_Funding_BE/blob/develop/src/main/java/com/AiFunding/ToBi/dto/Home/UserRequestDto.java

해찬님이 말씀하신 부분이 이 부분인 것 같은데 코드가 중복이긴 하네요. HistoryRequestDto Class를사용하는 곳을 UserRequestDto로 대체하면 코드 중복을 피할 수 있을 것 같습니다 :)

2022-02-17 04:50 UTC, HoSeong0731 commented on src/main/java/com/AiFunding/ToBi/dto/Tab/History/HistoryRequestDto.java
> +}
추가로 첨언하자면 두 개의 기능을 동일 코드로 사용하더라도 ResponseDto의 종류는 여러 개 일 수 있습니다. UserRequestDto의 명칭을 좀 더 공통적인 의미로 변경해준 후 코드 중복을 제거하면 좋을 것 같아요 :)

2022-02-17 04:50 UTC, HoSeong0731 commented on src/main/java/com/AiFunding/ToBi/dto/Tab/History/HistoryResponseDto.java
> +}
해찬님께서 3번째로 말씀해주신 부분이 여긴 것 같은데 저는 오히려 History Response에 어떤 값이 추가로 더 필요할 수도 있으니, 해당 클래스를 미리 구현해두는 것은 괜찮을 것 같아요 :)

2022-02-17 04:53 UTC, HoSeong0731 commented
또 코드 중복이 되더라도 Request와 Response를 1:1 매칭을 시킬 건지 N:N 매칭을 시킬 건지는 논의가 필요할 것 같네요
1 : 1매칭
코드 중복이 될 수 있으나, 1:1 대응이기 때문에 어떤 코드와 대입되는지 비교적  알기 쉽다.

다 : 다 매칭
코드 중복을 없앨 수 있으나, 해당 1 : N 관계인지 N : 1 관계인지에 따라 네이밍에 신경써줘야 한다.

정도의 장단점이 있을 것 같습니다!

2022-02-19 13:55 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/dto/Tab/History/HistoryResponseDto.java
> +}
호성님 말이 맞는것 같습니다. 오늘 회의 결과이후로 호성님 말대로 남기는 것으로 진행하기로 했습니다 👍 

의견 감사합니다!!

2022-02-19 13:56 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/dto/Tab/History/HistoryRequestDto.java
> +}
이 코드에 대해서는 모든 POST들이 `customer_info_id` 와 `login_type` 을 가져가기 때문에

제가 작성한 `UserRequsetDto`를 기본적으로 사용하기로 하고, 추가적인 내용이 있을 경우에는 상속해서 사용하기로 결정이 났습니다 👍

2022-02-19 19:32 UTC, jiione approved these changes
:+1:

2022-02-21 14:49 UTC, HoSeong0731 approved these changes

2022-02-21 14:49 UTC, HoSeong0731 commented
확인해보시고 이상 없는 것 같으면 Merge 부탁드립니다 :)

2022-02-21 16:16 UTC, kwYoohae commented
@HoSeong0731 현재 해당 내용에 대해서 수정커밋이 없어서 머지를 못하는 상황입니다.

@JeonHyerim86 수정사항 반영 부탁드립니다.

2022-02-24 00:30 UTC, HoSeong0731 commented
@JeonHyerim86 혜림님도 재리뷰 필요할 때는 https://github.com/AI-Funding/AI_Funding_BE/pull/34 해당 PR의 코멘트들 참고해주시면 감사합니다 :)

2022-02-24 04:05 UTC, kwYoohae reviewed
#37 확인하시고 JSON 제대로 나오는지 보고 안나오면 수정 부탁드립니다.

2022-02-24 05:26 UTC, merged