Feature/#16 ai 현재종목탭구현
AI-Funding/AI_Funding_BE pull request #34
Opened 2022-02-19 13:43 UTC by JinSeoHan

Ai 현재종목탭에서 계좌정보를 POST로 넘겨줄 DTO를 생성했습니다.

2022-02-19 14:44 UTC, redman1234321 reviewed
확인했습니다

2022-02-21 01:31 UTC, HoSeong0731 commented on src/test/java/StuckInfoDtoTest.java
> +}
해당 클래스 필요한가요??

2022-02-21 01:32 UTC, HoSeong0731 approved these changes

2022-02-22 06:07 UTC, JinSeoHan commented on src/test/java/StuckInfoDtoTest.java
> +}
테스트용으로 작성했던것인데 삭제하는게 좋을까요

2022-02-23 00:08 UTC, HoSeong0731 commented on src/test/java/StuckInfoDtoTest.java
> +}
네네 삭제하는 게 좋을 것 같습니다.

2022-02-23 05:05 UTC, kwYoohae requested changes

2022-02-24 00:29 UTC, HoSeong0731 commented on src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
> +    @PostMapping("/ap")
@JinSeoHan 서진님은 코드 변경 후 Reviewers에 존재하는 re-request review 버튼을 클릭해 리뷰를 다시 요청해주세요 :)

@kwYoohae 해찬님은 리뷰 반영된 점 확인해주시고 requests changes를 풀어주셔야 강제 Merge 권한이 없으신 분들이 Merge 할 수 있습니다. 참고해주세요!

2022-02-24 05:07 UTC, JinSeoHan commented on src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
> +    @PostMapping("/ap")
@HoSeong0731 넵 확인했습니다

2022-02-24 05:59 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
> +    @PostMapping("/aipage")
`aipage`로 Controller를 가져가면 Ai-Page에 항목이 3개인데 다른 분들이 불편할 것 같습니다. 
차라리 Request 매핑을 `aipage`로 가져가는 것이 좋은것 같습니다. 

또한, `aipage`는 다른 단어이므로 하이픈같은 것으로 구분하는 것이 더 좋을 것 같습니다.

2022-02-24 06:00 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
> +    @PostMapping("/aipage")
https://devuna.tistory.com/79

참고하시면 더 좋으실것 같습니다.

2022-02-24 15:09 UTC, JinSeoHan commented on src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
> +    @PostMapping("/aipage")
넵 참고하여 수정하겠습니다!

2022-02-24 15:39 UTC, kwYoohae approved these changes

2022-02-24 15:39 UTC, merged