Feature/#16 ai 현재종목탭구현 [최종]
AI-Funding/AI_Funding_BE pull request #48
Opened 2022-03-05 13:00 UTC by JinSeoHan

### 구현목록

Service에 필요한 Repository와 Service를 구현하였고,

Ai 현재종목탭의 POST에 대한 Controller를 Service와 매핑시켰습니다.

### api주소
| 주소 | 메서드 |
| --- | --- |
| `api/ai-page/stockitems` | `POST`

### 받는값
~~~json
{
	"customer_info_id" : "1",
	"login_type" : "00"
}
~~~

### 넘겨주는값
~~~json
{
	"account" : [
		{
			"account_name" : "계좌 이름",
			"stock" : [
				{
					"stock_name" : "주식이름",
					"current_price" : "현재가",
					"stock_price_change" : "전일종가 대비 현재가",
					"stock_rate_chagne" : "전일종가 대비 변동률",
					"stock_change" : "상승 하락 변동률"
					"stock_detail" : [
							{
								"end_price" : "현재 종가",
								"create_at" : "당일 날짜"
							},
							{
								"end_price" : "현재 종가",
								"create_at" : "당일 날짜"
							}
					]
				}
			]
		}
	]
}
~~~

2022-03-06 04:20 UTC, kwYoohae requested changes
<img width="836" alt="image" src="https://user-images.githubusercontent.com/74089271/156909035-51e6d8c4-2eee-47a4-a10c-4e32a1a38ca5.png">
현재 다음과 같이 쓰셨는데 모든 JSON은 카멜케이스로 하자고 했던것이 기억납니다. 그렇기 때문에 모든 값들을 다 수정하시는 것이 맞는것 같습니다. 

또한, `end_price`에 대한 변수명이 모호합니다. 직역하면 종가입니다. 하지만 **현재 종가**라고 되어있는데 이는 `now_price`라고 해석할 수 있습니다. 그점에 대해서 잘못 적으신것 같습니다. 확인부탁드립니다. 

PR 수고많으셨습니다. 수정부탁드립니다. 😄

2022-03-06 04:20 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            Integer yesterdayStockPrice = stockPriceByDayEntities.get(stockPriceByDayEntities.size()-1).getEndPrice();//어제주식가격
`yesterdayStockPrice` 를 구할때 `stockPriceByDayEntities`를 가져오는걸로 알고 있습니다. 

하지만 `stockPriceByDayEntities`를 구할때 인자로는 어제의 시작날짜와 어제의 마지막날짜를 넣었습니다. 

하지만 우리가 현재 `stockPriceByDay`의 `endPrice`에 대한 컬럼의 값은 **전일 종가**입니다.
<img width="257" alt="image" src="https://user-images.githubusercontent.com/74089271/156908837-c3ebb846-6077-4add-8604-d8c12e4bea0e.png">
그렇다는 것은 오늘에 대한 정보를 구해야하지 않을까요?

2022-03-06 04:20 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            Integer stockPriceChange = todayStockPrice * stock.getStockAmount() - yesterdayStockPrice * stock.getStockAmount();//어제주식가격 대비 상승가격
**어제 주식 가격 대비 상승가격** 이라는 말은 
<img width="407" alt="image" src="https://user-images.githubusercontent.com/74089271/156908681-62e4365d-4617-4133-82eb-0db9e2c3964d.png">
다음 사진에서 **1500**원 부분이 아닌가요?? 

그렇다는 것은 한 주당 주식가격 아닌가요? 

하지만 현재 **오늘의 주식가격 * 주식의 양 - 어제의 주식가격 * 주식의 양**은 의미가 없어보입니다. 

그래서 제 생각에는 **오늘의 주식가격 - 어제의 주식가격**만해도 값을 구할 수 있지 않을까요?

주식의 양은 중복되는 값이기 때문에 빼도 상관없는 것 같습니다.

2022-03-06 04:20 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +        //List<StockPriceByDayEntity> stockPriceByDay = stockPriceByDayRepository.findByStockEntityAndCreateAtBetween()
안쓰는 코드는 주석처리말고 지워주시면 될것 같습니다 👍

2022-03-06 04:20 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            StockPriceByDayEntity stockPriceByDay = stockPriceByDayEntities.get(stockPriceByDayEntities.size()-1);
왜 `stockPriceByDayEntites`를 가져올 때 `size() - 1`을 하는지 궁금합니다 !! 😄

2022-03-06 04:20 UTC, kwYoohae commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            List<StockPriceByDayEntity> stockPriceByDayEntities = stockDetail.getStock().getStockPriceByDayEntities();
정보를 가져올 때 이렇게 하면 모든 날짜에 대한 `stockPriceByDayEntity`를 가져오게 됩니다. 

많은 양이고 우리는 `end_price`를 넘겨줘야하는 것은 알고있습니다. 

근데 궁금한점이 `end_price`가 현재 종가를 넘겨주는것이 맞을까요? 맞다면 **현재 종가**라는 말은 **현재 가격**이라는 말과 동일 시 할 수 있는데 변수가 햇갈릴것 같습니다. 

변수를 수정 혹은 잘못 이해하셨다면 코드를 고치셔야 할것같습니다. 

1. `end_price`가 **현재 종가**라면 현재가를 가져와야합니다. 
2. `end_price`가 **전일 종가**라면 날짜에 따라서 오늘있는 값만 가져와서 가격을 가져와야 합니다. 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/74089271/156909028-f5b4a376-22bf-4f8f-a8d7-0ad0d9176a21.png">

2022-03-06 04:45 UTC, JinSeoHan commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            StockPriceByDayEntity stockPriceByDay = stockPriceByDayEntities.get(stockPriceByDayEntities.size()-1);
주식가격변동내역은 일정 시간대별로 DB에 추가되기 때문에 항상 List의 마지막에는 마지막으로 기록한 주식가격변동내용이 저장되어 있다고 판단하였고 마지막으로 저장되어있는 주식가격변동내역을 가져오기 위해 사용하였습니다

2022-03-06 06:26 UTC, JinSeoHan commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            StockPriceByDayEntity stockPriceByDay = stockPriceByDayEntities.get(stockPriceByDayEntities.size()-1);
다시 확인 하였는데 제가 구현한 부분에 오류가 있는 것 같습니다.
해당 주식에 대한 날짜별 종가 기록들을 배열로 보내줘야하는데  `size() -1`을 하게되면 전날 마지막에 기록된 종가값만 반환하게 될 것 같습니다.
해당 주식의 시간대별 가격의 기록들을 배열로 보내주는 것으로 수정하도록 하겠습니다

2022-03-06 06:40 UTC, JinSeoHan commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            List<StockPriceByDayEntity> stockPriceByDayEntities = stockDetail.getStock().getStockPriceByDayEntities();
`stock_detail` 같은 경우 주가흐름 그래프 표현시 필요한 날짜시간별 주식가격 데이터로 알고있습니다.

그런데 end_price라는 이름을 사용하면 해찬님 말씀대로 헷갈릴것 같네요.

카멜케이스도 포함하여 아래와같이 수정하도록 하겠습니다!

<img width="821" alt="image" src="https://user-images.githubusercontent.com/87526189/156912254-466019fd-a8e9-4373-bd58-936759b299b9.png">

2022-03-06 08:34 UTC, JinSeoHan commented on src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
> +            Integer yesterdayStockPrice = stockPriceByDayEntities.get(stockPriceByDayEntities.size()-1).getEndPrice();//어제주식가격
오늘에 대한 정보로 전일종가 데이터를 찾아서 사용하는 것으로 수정하겠습니다!

2022-03-07 00:14 UTC, HoSeong0731 approved these changes
고생하셨습니다 :) 활발한 리뷰가 이루어지는 것 같아요

2022-03-07 02:22 UTC, jiione approved these changes
고생하셨습니다~!

2022-03-09 03:31 UTC, kwYoohae approved these changes

2022-03-09 03:31 UTC, merged